---
- name: Create netbox postgresql database
  community.postgresql.postgresql_db:
    name: "{{ netbox_database }}"
  become: true
  become_user: "{{ postgresql_user }}"

- name: Revoke PUBLIC permissions on netbox postgresql database
  community.postgresql.postgresql_privs:
    database: "{{ netbox_database }}"
    role: PUBLIC
    type: database
    privs: ALL
    state: absent
  become: yes
  become_user: "{{ postgresql_user }}"

- name: Revoke PUBLIC permissions for public schema on netbox postgresql database
  community.postgresql.postgresql_privs:
    database: "{{ netbox_database }}"
    role: PUBLIC
    type: schema
    objs: public
    privs: ALL
    state: absent
  become: yes
  become_user: "{{ postgresql_user }}"

- name: Create netbox postgresql user
  community.postgresql.postgresql_user:
    name: "{{ netbox_database_user }}"
    password: "{{ netbox_database_password | default(omit) }}"
    role_attr_flags: NOSUPERUSER,NOCREATEROLE,NOCREATEDB
  no_log: true
  become: true
  become_user: "{{ postgresql_user }}"

- name: Grant all to netbox postgresql database for netbox user
  community.postgresql.postgresql_privs:
    db: postgres
    type: database
    obj: "{{ netbox_database }}"
    role: "{{ netbox_database_user }}"
    privs: ALL
  become: true
  become_user: "{{ postgresql_user }}"

- name: Grant all to public schema for netbox postgresql user
  community.postgresql.postgresql_privs:
    db: "{{ netbox_database }}"
    role: "{{ netbox_database_user }}"
    type: schema
    objs: public
    privs: ALL
  become: yes
  become_user: "{{ postgresql_user }}"
